// Dummy values
ext.signing = [
        enabled       : false,
        storeFilePath : '.keystore',
        storePassword : 'password',
        keyAlias      : 'alias',
        keyPassword   : 'password',
]

apply plugin: 'com.android.application'
if (file('signing.gradle').exists()) {
    apply from: 'signing.gradle'
}

def getRevision() {
    def proc = ['git', 'rev-parse', '--short=7', 'HEAD'].execute(null, rootDir)
    proc.waitFor()
    return proc.text.trim()
}
ext.revision = getRevision()

android {
    namespace "org.openxcom.extended"
    compileSdk 35
    ndkVersion "30.0.14904198"

    externalNativeBuild {
        cmake {
            path "src/main/jni/CMakeLists.txt"
        }
    }

    defaultConfig {
        applicationId "org.libsdl.openxcom"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_static", "-DANDROID_ARM_MODE=arm", "-DOPENXCOM_VERSION_STRING=${project.revision}"
                abiFilters "armeabi-v7a", "x86", "x86_64", "arm64-v8a"
                cppFlags "-std=c++17", "-fexceptions", "-frtti"
            }
        }
    }

    if (project.signing.enabled) {
        signingConfigs {
            release {
                storeFile file(project.signing.storeFilePath)
                storePassword project.signing.storePassword
                keyAlias project.signing.keyAlias
                keyPassword project.signing.keyPassword
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
                externalNativeBuild {
                    cmake {
                        cFlags "-O3", "-ffast-math"
                        cppFlags "-O3", "-ffast-math"
                    }
                }
            }
        }
        applicationVariants.all { variant ->
            variant.outputs.all {
                if (outputFileName.endsWith('.apk')) {
                    outputFileName = outputFileName.replace("app-release", "OpenXcom-v1.0-g${project.revision}")
                }
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }

    lint {
        checkReleaseBuilds false
    }
}

def getFolder(resource) {
    return file('src/main/jni/OpenXcom/bin/' + resource)
}

['common', 'standard', 'UFO', 'TFTD'].eachWithIndex { String res, int index ->
    tasks.register("zip${res}", Zip) {
        destinationDirectory = file('src/main/assets')
        archiveFileName = "${index}_${res}.zip"
        from getFolder(res)
        into res
        doFirst { println("Packing ${res}...") }
    }
}

tasks.register('zipTranslations', Zip) {
    destinationDirectory = file('src/main/assets')
    archiveFileName = '7_translations.zip'
    from getFolder('translations/output')
    into 'translations'
    doFirst { println('Packing translations...') }
}

tasks.register('packBin') {
    description = 'Update data files.'
    dependsOn 'zipcommon', 'zipstandard', 'zipUFO', 'zipTFTD', 'zipTranslations'
}

tasks.withType(Zip).configureEach {
    doLast {
        ant.checksum file: archiveFile.get().asFile, algorithm: 'MD5'
    }
}

afterEvaluate {
    tasks.named('preBuild') {
        dependsOn('packBin')
    }
}
